# standard jekyll configuration

permalink: none
pygments: true
exclude: ['Rakefile', 'README.md']
markdown: rdiscount
root_dir: "Jekyll-Bootstrap-Template"

# configuration required for some pages
baseurl: "Jekyll-Bootstrap-Template"
domain: webcane.github.com
title: webcane on gitHub pages
author: Mikhail Niedre
email: webcane@ya.ru

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
 username: webcane

# disqus:
#   id: disqusid
